config/routes.rb
Rails.application.routes.draw do

  namespace :users do
    get 'top/index'
    resources :bookmarks, only: [:index]
    resources :borrowings
    resources :borrowing_histories, only: [:index]
    resources :additions, only: [:destroy, :create]  
    resources :books, only: [:show] do
      resources :book_reservations
      resources :reviews, only: [:create, :update, :edit, :destroy]
      resources :bookmarks, only: [:create, :destroy]
      resources :stocks, only: [:show] do
        resources :stock_reservations
        resources :borrowing_histories, except: [:index]
      end
    end
    resources :new_books, only: [:index, :new, :create, :destroy]
  end

  namespace :admins do
    get 'top/index'
    resources :borrowings, only: [:index, :create]
    resources :borrowing_histories, only: [:index, :create]
    resources :bookmarks, only: [:index]
    resources :authors, except: [:show]
    resources :genres, except: [:show]
    resources :publishers, except: [:show]
    resources :additions, only: [:delete]
    resources :addition_histories, only: [:create]
    resources :new_books, only: [:index, :create]
    resources :books, except: [:index] do
      resources :book_reservations
      resources :stocks, only: [:create, :destroy] do
        resources :stock_reservations
      end
    end
  end

  devise_for :admins, :controllers => {
    :sessions      => "admins/sessions",
    :registrations => "admins/registrations",
    :passwords     => "admins/passwords"
  }

  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords"
  }

  root to: "users/top#index"
  mount API::Root => '/'

end

app/models/addition.rb
class Addition < ActiveRecord::Base
  belongs_to :user
  belongs_to :new_book
  belongs_to :addition_status
end

app/models/addition_history.rb
class AdditionHistory < ActiveRecord::Base
  belongs_to :user
  belongs_to :new_book
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  belongs_to :publisher
  belongs_to :genre
  has_many :stocks, dependent: :destroy

  has_many :reviews, dependent: :destroy
  has_many :review_users, through: :reviews, :source => 'user'

  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_users, through: :bookmarks, :source => 'user'

  has_many :book_reservations
  has_many :reservation_users, through: :book_reservations, :source => 'user'



  def borrowing_records
    BorrowingHistory.where(stock_id: self.stocks).order("created_at DESC")
  end

  def borrowing_stocks
    Borrowing.where(stock_id: self.stocks)
  end

  def reserved_stocks
    StockReservation.where(stock_id: self.stocks)
  end


  def remaining_stocks
   borrowing_stock_ids = self.borrowing_stocks.pluck(:stock_id)
   reserved_stock_ids = self.reserved_stocks.pluck(:stock_id)
   remaining_stock_ids = self.stock_ids - borrowing_stock_ids - reserved_stock_ids
   stocks.where(id: remaining_stock_ids)
  end


end

app/models/book_reservation.rb
class BookReservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/models/borrowing.rb
class Borrowing < ActiveRecord::Base
  belongs_to :user
  belongs_to :stock
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :books, dependent: :destroy
end

app/models/new_book.rb
class NewBook < ActiveRecord::Base
  has_many :additions, dependent: :destroy
  accepts_nested_attributes_for :additions
  has_many :users, through: :additions, dependent: :destroy

  has_many :addition_histories
  has_many :users, through: :addition_histories
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :books, dependent: :destroy
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :book

  has_one :stock_reservation
  has_one :reservation_user, through: :stock_reservation, :source => 'user'

  has_one :borrowing
  has_one :borrowing_user, through: :borrowing, :source => 'user'

  has_many :borrowing_histories
  has_many :borrowing_history_users, through: :borrowing_histories, :source => 'user'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :name, presence:{ message: "を入力してください"}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  has_many :review_books, through: :reviews, :source => 'book' 

  has_many :bookmarks
  has_many :bookmark_books, through: :bookmarks, :source => 'book'

  has_many :additions
  has_many :new_books, through: :additions

  has_many :addition_histories
  has_many :new_books, through: :addition_histories

  has_many :borrowings
  has_many :borrowing_stocks, through: :borrowings, :source => 'stock'

  has_many :borrowing_histories
  has_many :borrowing_history_stocks, through: :borrowing_histories, :source => 'stock'

  has_many :stock_reservations
  has_many :reservation_stocks, through: :stock_reservations, :source => 'stock'

  has_many :book_reservations
  has_many :reservation_books, through: :book_reservations, :source => 'book'


  def stocks_in_use
    self.borrowings.count + self.stock_reservations.count + self.book_reservations.count
  end

  def expired_borrowings
    self.borrowings.where("return_at < ?", DateTime.now).first
  end

  def stock_borrow(stocks)
    self.borrowings.find_by(stock_id: stocks.pluck(:id))
  end

  def stock_reserv(stocks)
    self.stock_reservations.find_by(stock_id: stocks.pluck(:id))
  end

  def book_reserv(book)
    self.book_reservations.find_by(book_id: book.id)
  end


end

app/controllers/admins/top_controller.rb
class Admins::TopController < AdminsController
  def index
    @book_search = Book.search(params[:q])
    @books = @book_search.result.includes(:author, :publisher, :genre)
    @stock = Stock.new
  end
end

app/controllers/users/top_controller.rb
class Users::TopController < UsersController
  def index
    @user = current_user
    @book_search = Book.search(params[:q])
    @books = @book_search.result.includes(:author, :publisher, :genre)
  end
end

app/helpers/admins/top_helper.rb
module Admins::TopHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/books_helper.rb
module BooksHelper

  def status(stock)
    if stock.borrowing
      "貸出し中"
    else 
      if stock.stock_reservation
        "取り置き中"
      else
        "在庫あり"
      end
    end
  end

  def status_for_admins(stock)
    if stock.borrowing
      "貸出し期限: #{stock.borrowing.return_at.to_date} #{stock.borrowing.user.name}"
    else 
      if stock.stock_reservation
      "取り置き期限: #{stock.stock_reservation.invalid_at.to_date} #{stock.stock_reservation.user.name}"
      else
        "在庫あり"
      end
    end
  end


  def status_select(user, stocks, book, book_reservation, stock_reservation)
    if user.stock_borrow(stocks) 
      "返却期限: #{user.stock_borrow(stocks).return_at.to_date}" 
    else 
      if user.stock_reserv(stocks) 
        "取り置き有効期限: #{user.stock_reserv(stocks).invalid_at.to_date}"
        link_to "予約取り消し", users_book_stock_stock_reservation_path(book.id, user.stock_reserv(stocks).stock_id, user.stock_reserv(stocks).id), method: :delete, data: {confirm: "Are you sure??"} 
      else 
        if user.book_reserv(book) 
          "現在予約中です。後日また連絡いたします。"
          link_to "予約取り消し", users_book_book_reservation_path(book.id, user.book_reserv(book).id), method: :delete, data: {confirm: "Are you sure??"} 
        else 
          unless book.remaining_stock 
            form_for book_reservation, url: users_book_book_reservations_path(book.id) do |f| 
              f.submit :この本を予約する 
            end 
          else 
            form_for stock_reservation, url: users_book_stock_stock_reservations_path(book.id, book.remaining_stock.id) do |f| 
              f.submit :この本を予約する 
            end 
          end 
        end 
      end 
    end 
  end

end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users/top_helper.rb
module Users::TopHelper
end

app/views/admins/top/index.html.erb
<h1>管理者画面</h1><br>

<div class="navbar navbar-default">
  <div class="navbar-inner">
    <ul class="nav">
      <li class="now"><%= link_to "図書検索画面"%></li>
      <li><%= link_to "図書追加", new_admins_book_path %></li>
      <li><%= link_to "図書リクエスト", admins_new_books_path %></li>
      <li><%= link_to "ブックマーク", admins_bookmarks_path %></li>
      <li><%= link_to "貸出履歴", admins_borrowing_histories_path %></li>
      <li><%= link_to "貸出/予約状況", admins_borrowings_path %></li>
    </ul>
  </div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">
    <h2>図書検索</h2>
  </div>

  <div class="panel-body">
    <div class="search_field">
      <%= search_form_for @book_search, url: admins_top_index_path do |f| %>
        <%= f.label :title_cont, "タイトル" %>
        <%= f.text_field :title_cont %><br><br>
        <%= f.label :author_author_name_cont, "著者" %>
        <%= f.text_field :author_author_name_cont %><br><br>
        <%= f.label :publisher_publisher_name_cont, "出版社" %>
        <%= f.text_field :publisher_publisher_name_cont %><br><br>
        <%= f.label :genre_genre_name_cont, "分野" %>
        <%= f.text_field :genre_genre_name_cont %><br><br>
        <div class="search_actions"><%= f.submit "Search" %></div>
      <% end %>
    </div>
  </div>
</div><br>

<div class="search_container">
  <h2>検索結果</h2><br>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>タイトル</th>
        <th>著者</th>
        <th>出版社</th>
        <th>分野</th>
        <th>保有冊数</th>
        <th>在庫冊数</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= link_to book.title, admins_book_path(book.id) %> </td>
          <td><%= book.author.author_name %></td>
          <td><%= book.publisher.publisher_name %></td>
          <td><%= book.genre.genre_name %></td>
          <td><%= book.stocks.count %></td>
          <td><%= book.remaining_stocks.count %></td>
          <td>
            <%= button_to "編集", edit_admins_book_path(book.id), :method => :get %> 
          </td>
          <td>
            <%= button_to "削除", admins_book_path(book.id), method: :delete, data: {confirm: "本当に削除しますか？"}, :method => :delete %> 
          </td>
          <td>
            <%= form_for @stock, url: admins_book_stocks_path(book.id) do |f| %> 
              <%= f.submit :入荷 %>
            <% end %>
          </td>
        </tr>
    </tbody>
  <% end %>
  </table>
</div>