config/routes.rb
Rails.application.routes.draw do

  namespace :users do
    get 'top/index'
    resources :bookmarks, only: [:index]
    resources :borrowings
    resources :borrowing_histories, only: [:index]
    resources :additions, only: [:destroy, :create]  
    resources :books, only: [:show] do
      resources :book_reservations
      resources :reviews, only: [:create, :update, :edit, :destroy]
      resources :bookmarks, only: [:create, :destroy]
      resources :stocks, only: [:show] do
        resources :stock_reservations
        resources :borrowing_histories, except: [:index]
      end
    end
    resources :new_books, only: [:index, :new, :create, :destroy]
  end

  namespace :admins do
    get 'top/index'
    resources :borrowings, only: [:index, :create]
    resources :borrowing_histories, only: [:index, :create]
    resources :bookmarks, only: [:index]
    resources :authors, except: [:show]
    resources :genres, except: [:show]
    resources :publishers, except: [:show]
    resources :additions, only: [:delete]
    resources :addition_histories, only: [:create]
    resources :new_books, only: [:index, :create]
    resources :books, except: [:index] do
      resources :book_reservations
      resources :stocks, only: [:create, :destroy] do
        resources :stock_reservations
      end
    end
  end

  devise_for :admins, :controllers => {
    :sessions      => "admins/sessions",
    :registrations => "admins/registrations",
    :passwords     => "admins/passwords"
  }

  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords"
  }

  root to: "users/top#index"
  mount API::Root => '/'

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :books, dependent: :destroy
end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < AdminsController
  before_action :set_genre, only: [:edit, :update, :destroy] 

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    if Genre.create(genre_params)
      redirect_to admins_genres_path, notice: "新たな分野を追加しました"
    end
  end

  def edit
  end

  def update
    if @genre.update(genre_params) 
      redirect_to admins_genres_path, notice: "分野情報を更新しました"
    end
  end

  def destroy
    @genre.destroy
    redirect_to admins_genres_path
  end

  private

    def genre_params
      params.require(:genre).permit(:genre_name)
    end

    def set_genre
      @genre = Genre.find(params[:id])
    end

end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/admins/genres/edit.html.erb
<h1>管理者画面</h1><br>

<div class="navbar navbar-default">
  <div class= "navbar-inner">
    <ul class="nav">
      <li><%= link_to "図書検索画面", admins_top_index_path %></li>
      <li><%= link_to "図書追加", new_admins_book_path %></li>
      <li><%= link_to "図書リクエスト", admins_new_books_path %></li>
      <li><%= link_to "ブックマーク", admins_bookmarks_path %></li>
      <li><%= link_to "貸出履歴", admins_borrowing_histories_path %></li>
      <li><%= link_to "貸出/予約状況", admins_borrowings_path %></li>
      <li><%= link_to "分野一覧へ", admins_genres_path %></li>
    </ul>
  </div>
</div>

<div class="editer_container">
  <%= form_for @genre, url: admins_genre_path do |f| %>
    <%= f.label :分野名 %>
    <%= f.text_field :genre_name %>
    <%= f.submit :分野名の編集 %>
  <% end %>
</div>

app/views/admins/genres/index.html.erb
<h1> 管理者画面 </h1><br>


<div class="navbar navbar-default">
  <div class= "navbar-inner">
    <ul class="nav">
      <li><%= link_to "図書検索画面", admins_top_index_path %></li>
      <li><%= link_to "図書追加", new_admins_book_path %></li>
      <li><%= link_to "図書リクエスト", admins_new_books_path %></li>
      <li><%= link_to "ブックマーク", admins_bookmarks_path %></li>
      <li><%= link_to "貸出履歴", admins_borrowing_histories_path %></li>
      <li><%= link_to "貸出/予約状況", admins_borrowings_path %></li>
    </ul>
  </div>
</div><br>

<div class="nature_create">
  <%= form_for @genre, url:admins_genres_path do |f| %>

    <%= f.label :分野名 %>
    <%= f.text_field :genre_name %>
    <%= f.submit :分野の追加 %>

  <% end %>
</div><br><br>

<div class="nature_container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>分野名</th>
        <th>更新日時</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @genres.each do |genre| %>
        <tr>
          <td><%= genre.genre_name %> </td>
          <td><%= genre.updated_at %></td>
          <td>
            <%= button_to "編集", edit_admins_genre_path(genre.id), :method => :get %>
          </td>
          <td>
            <%= button_to "削除", admins_genre_path(genre.id), method: :delete, data: {confirm: "本当に削除しますか？"}, :method => :delete %>
          </td>
        </tr>
    </tbody>
  <% end %>
  </table>
</div>