config/routes.rb
Rails.application.routes.draw do

  namespace :users do
    get 'top/index'
    resources :bookmarks, only: [:index]
    resources :borrowings
    resources :borrowing_histories, only: [:index]
    resources :additions, only: [:destroy, :create]  
    resources :books, only: [:show] do
      resources :book_reservations
      resources :reviews, only: [:create, :update, :edit, :destroy]
      resources :bookmarks, only: [:create, :destroy]
      resources :stocks, only: [:show] do
        resources :stock_reservations
        resources :borrowing_histories, except: [:index]
      end
    end
    resources :new_books, only: [:index, :new, :create, :destroy]
  end

  namespace :admins do
    get 'top/index'
    resources :borrowings, only: [:index, :create]
    resources :borrowing_histories, only: [:index, :create]
    resources :bookmarks, only: [:index]
    resources :authors, except: [:show]
    resources :genres, except: [:show]
    resources :publishers, except: [:show]
    resources :additions, only: [:delete]
    resources :addition_histories, only: [:create]
    resources :new_books, only: [:index, :create]
    resources :books, except: [:index] do
      resources :book_reservations
      resources :stocks, only: [:create, :destroy] do
        resources :stock_reservations
      end
    end
  end

  devise_for :admins, :controllers => {
    :sessions      => "admins/sessions",
    :registrations => "admins/registrations",
    :passwords     => "admins/passwords"
  }

  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords"
  }

  root to: "users/top#index"
  mount API::Root => '/'

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books, dependent: :destroy
end

app/controllers/admins/authors_controller.rb
class Admins::AuthorsController < AdminsController
  before_action :set_author, only: [:edit, :update, :destroy] 

  def index
    @authors = Author.all
    @author = Author.new
  end

  def create
    if Author.create(author_params)
      redirect_to admins_authors_path, notice: "新たな著者を登録しました"
    end
  end

  def edit
  end

  def update
    if @author.update(author_params) 
      redirect_to admins_authors_path, notice: "著者情報を更新しました"
    end
  end

  def destroy
    @author.destroy
    redirect_to admins_authors_path
  end

  private

    def author_params
      params.require(:author).permit(:author_name)
    end

    def set_author
      @author = Author.find(params[:id])
    end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/admins/authors/edit.html.erb
<h1> 管理者画面 </h1><br>

<div class="navbar navbar-default">
  <div class= "navbar-inner">
    <ul class="nav">
      <li><%= link_to "図書検索画面", admins_top_index_path %></li>
      <li><%= link_to "図書追加", new_admins_book_path %></li>
      <li><%= link_to "図書リクエスト", admins_new_books_path %></li>
      <li><%= link_to "ブックマーク", admins_bookmarks_path %></li>
      <li><%= link_to "貸出履歴", admins_borrowing_histories_path %></li>
      <li><%= link_to "貸出/予約状況", admins_borrowings_path %></li>
      <li><%= link_to "著者一覧へ", admins_authors_path %></li>
    </ul>
  </div>
</div>

<div class="editer_container">
  <%= form_for @author, url: admins_author_path do |f| %>
    <%= f.label :著者名 %>
    <%= f.text_field :author_name %>
    <%= f.submit :著者名の編集 %>
  <% end %>
</div>

app/views/admins/authors/index.html.erb
<h1> 管理者画面 </h1><br>

<div class="navbar navbar-default">
  <div class= "navbar-inner">
    <ul class="nav">
      <li><%= link_to "図書検索画面", admins_top_index_path %></li>
      <li><%= link_to "図書追加", new_admins_book_path %></li>
      <li><%= link_to "図書リクエスト", admins_new_books_path %></li>
      <li><%= link_to "ブックマーク", admins_bookmarks_path %></li>
      <li><%= link_to "貸出履歴", admins_borrowing_histories_path %></li>
      <li><%= link_to "貸出/予約状況", admins_borrowings_path %></li>
    </ul>
  </div>
</div><br>

<div class="nature_create">
  <%= form_for @author, url: admins_authors_path do |f| %>

    <%= f.label :著者名 %>
    <%= f.text_field :author_name %>
    <%= f.submit :著者の追加 %>

  <% end %>
</div><br><br>

<div class="nature_container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>著者名</th>
        <th>更新日</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @authors.each do |author| %>
        <tr>
          <td><%= author.author_name %> </td>
          <td><%= author.updated_at.to_date %></td>
          <td>
            <%= button_to "編集", edit_admins_author_path(author.id), :method => :get %>
          </td>
          <td>
            <%= button_to "削除", admins_author_path(author.id), method: :delete, data: {confirm: "本当に削除しますか？"}, :method => :delete %>
          </td>
        </tr>
    </tbody>
  <% end %>
  </table>
</div>