config/routes.rb
Rails.application.routes.draw do

  namespace :users do
    get 'top/index'
    resources :bookmarks, only: [:index]
    resources :borrowings
    resources :borrowing_histories, only: [:index]
    resources :additions, only: [:destroy, :create]  
    resources :books, only: [:show] do
      resources :book_reservations
      resources :reviews, only: [:create, :update, :edit, :destroy]
      resources :bookmarks, only: [:create, :destroy]
      resources :stocks, only: [:show] do
        resources :stock_reservations
        resources :borrowing_histories, except: [:index]
      end
    end
    resources :new_books, only: [:index, :new, :create, :destroy]
  end

  namespace :admins do
    get 'top/index'
    resources :borrowings, only: [:index, :create]
    resources :borrowing_histories, only: [:index, :create]
    resources :bookmarks, only: [:index]
    resources :authors, except: [:show]
    resources :genres, except: [:show]
    resources :publishers, except: [:show]
    resources :additions, only: [:delete]
    resources :addition_histories, only: [:create]
    resources :new_books, only: [:index, :create]
    resources :books, except: [:index] do
      resources :book_reservations
      resources :stocks, only: [:create, :destroy] do
        resources :stock_reservations
      end
    end
  end

  devise_for :admins, :controllers => {
    :sessions      => "admins/sessions",
    :registrations => "admins/registrations",
    :passwords     => "admins/passwords"
  }

  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords"
  }

  root to: "users/top#index"
  mount API::Root => '/'

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  belongs_to :publisher
  belongs_to :genre
  has_many :stocks, dependent: :destroy

  has_many :reviews, dependent: :destroy
  has_many :review_users, through: :reviews, :source => 'user'

  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_users, through: :bookmarks, :source => 'user'

  has_many :book_reservations
  has_many :reservation_users, through: :book_reservations, :source => 'user'



  def borrowing_records
    BorrowingHistory.where(stock_id: self.stocks).order("created_at DESC")
  end

  def borrowing_stocks
    Borrowing.where(stock_id: self.stocks)
  end

  def reserved_stocks
    StockReservation.where(stock_id: self.stocks)
  end


  def remaining_stocks
   borrowing_stock_ids = self.borrowing_stocks.pluck(:stock_id)
   reserved_stock_ids = self.reserved_stocks.pluck(:stock_id)
   remaining_stock_ids = self.stock_ids - borrowing_stock_ids - reserved_stock_ids
   stocks.where(id: remaining_stock_ids)
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :name, presence:{ message: "を入力してください"}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  has_many :review_books, through: :reviews, :source => 'book' 

  has_many :bookmarks
  has_many :bookmark_books, through: :bookmarks, :source => 'book'

  has_many :additions
  has_many :new_books, through: :additions

  has_many :addition_histories
  has_many :new_books, through: :addition_histories

  has_many :borrowings
  has_many :borrowing_stocks, through: :borrowings, :source => 'stock'

  has_many :borrowing_histories
  has_many :borrowing_history_stocks, through: :borrowing_histories, :source => 'stock'

  has_many :stock_reservations
  has_many :reservation_stocks, through: :stock_reservations, :source => 'stock'

  has_many :book_reservations
  has_many :reservation_books, through: :book_reservations, :source => 'book'


  def stocks_in_use
    self.borrowings.count + self.stock_reservations.count + self.book_reservations.count
  end

  def expired_borrowings
    self.borrowings.where("return_at < ?", DateTime.now).first
  end

  def stock_borrow(stocks)
    self.borrowings.find_by(stock_id: stocks.pluck(:id))
  end

  def stock_reserv(stocks)
    self.stock_reservations.find_by(stock_id: stocks.pluck(:id))
  end

  def book_reserv(book)
    self.book_reservations.find_by(book_id: book.id)
  end


end

app/controllers/admins/books_controller.rb
class Admins::BooksController < AdminsController
  before_action :set_book,  only: [:edit, :update, :destroy]
  before_action :set_admin, only: [:new, :create, :update, :destroy]

  def show
    @book = Book.includes(:author, :publisher, :genre, stocks: [borrowing: [:user], stock_reservation: [:user]]).find(params[:id])
    @reviews = @book.reviews.where(params[:id]).includes(:user)
  end

  def new
    @book = Book.new
  end

  def create 
    if Book.create(book_params)
      redirect_to admins_top_index_path(@admin.id), notice: "新たな本を追加しました"
    end
  end

  def edit
  end

  def update
    if @book.update(book_params) 
      redirect_to admins_book_path(@book.id), notice: "図書情報を更新しました"
    end
  end

  def destroy
    @book.destroy
    redirect_to admins_top_index_path(@admin.id), notice: "図書情報を削除しました"
  end

  private

  def set_admin
    @admin = current_admin
  end

    def book_params
      params.require(:book).permit(:title, :author_id, :publisher_id, :genre_id)
    end

    def set_book
      @book = Book.find(params[:id])
    end

end

app/controllers/users/additions_controller.rb
class Users::AdditionsController < UsersController

  def destroy 
    ActiveRecord::Base.transaction do
      addition = Addition.find(params[:id])
      addition.new_book.destroy
      addition.destroy
    end
    redirect_to users_new_books_path
  end


end

app/controllers/users/book_reservations_controller.rb
class Users::BookReservationsController < UsersController

  before_action :set_book

  def create 
    @book.book_reservations.create(user_id: current_user.id)
    redirect_to users_book_path(@book.id)
  end

  def destroy
    @user = current_user
    @user.book_reservations.find(params[:id]).destroy
    redirect_to users_book_path(@book.id)
  end

  private
    
    def set_book
      @book = Book.find(params[:book_id])
    end


end

app/controllers/users/bookmarks_controller.rb
class Users::BookmarksController < UsersController
  before_action :set_book, only: [:create, :destroy]


  def index
    @user = current_user
    @bookmarks = Bookmark.where(user_id: @user.id).includes(book: [:author, :publisher, :genre])
  end

  def create
    @book.bookmarks.create(user_id: current_user.id)
    redirect_to users_book_path(@book.id), notice: "ブックマークに追加しました"
  end

  def destroy
    @book.bookmarks.find(params[:id]).destroy
    redirect_to users_book_path(@book.id), notice: "ブックマークから削除しました"
  end


  private 

    def set_book
      @book = Book.find(params[:book_id])
    end

    def bookmark_params
      @user = current_user
      params.require(:bookmark).merge(user_id: @user.id)
    end

end 

app/controllers/users/books_controller.rb
class Users::BooksController < UsersController
  before_action :set_book,  only: [:show]

  def show
    @user = current_user
    @book = Book.includes(:author, :genre, :publisher, reviews: [:user]).find(params[:id])
    @bookmark = Bookmark.new
    @user_bookmark = @book.bookmarks.find_by(user_id: @user.id)
    @review = Review.new
    @book_reservation = BookReservation.new
    @stock_reservation = StockReservation.new
    @stocks = @book.stocks.includes(:borrowing, :stock_reservation)
    @all_stocks = Stock.all
  end


  private

    def book_params
      params.require(:book).permit(:title, :author_id, :publisher_id, :genre_id)
    end

    def set_book
      @book = Book.find(params[:id])
    end

end

app/controllers/users/borrowing_histories_controller.rb
class Users::BorrowingHistoriesController < UsersController

  def index
    user = current_user
    @borrowing_history_search = user.borrowing_histories.search(params[:q])
    @borrowing_histories = @borrowing_history_search.result.includes(stock: [book: [:author, :publisher, :genre]])
  end

end

app/controllers/users/borrowings_controller.rb
class Users::BorrowingsController < UsersController

  def index
    @user = User.includes(stock_reservations: [stock: [book: [:author, :publisher, :genre]]], book_reservations: [book: [:author, :publisher, :genre]], borrowings: [stock: [book: [:author, :publisher, :genre]]]).find(current_user.id) 
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/new_books_controller.rb
class Users::NewBooksController < UsersController

  def index 
    @user = User.includes(additions: [:new_book], addition_histories: [:new_book]).order("additions.created_at DESC").order("addition_histories.created_at DESC").find(current_user)
    @new_book = NewBook.new
  end

  def create
    @new_book = NewBook.new(new_book_params)
    @new_book.additions.build(user_id: current_user.id)
    @new_book.save
    redirect_to users_new_books_path, notice: "新規図書購入申し込み承りました"
  end




  private 
    def new_book_params
      params.require(:new_book).permit(:title, :author, :publisher, :genre_id)
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/reviews_controller.rb
class Users::ReviewsController < UsersController
  before_action :set_book
  before_action :set_review, only: [:edit, :update, :destroy]

  def create
    if @book.reviews.create(review_params)
      redirect_to users_book_path(@book.id), notice: "レビューを作成しました"
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to users_book_path(@review.book_id), notice: "レビューを更新しました"
    end
  end

  def destroy
    @review.destroy
    redirect_to users_book_path(@review.book_id)
  end

  private 

    def set_review
      @review = @book.reviews.find(params[:id])
    end

    def set_book
      @book = Book.find(params[:book_id])
    end

    def review_params
      @user = current_user
      params.require(:review).permit(:content).merge(user_id: @user.id)
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/stock_reservations_controller.rb
class Users::StockReservationsController < UsersController

  def create
    @book = Book.find(params[:book_id])
    StockReservation.create(stock_reservation_params)
    redirect_to users_book_path(@book.id)
  end


  def destroy
    @book = Book.find(params[:book_id])
    ActiveRecord::Base.transaction do
      StockReservation.find(params[:id]).destroy!
      reservation = @book.book_reservations.all.order("created_at").first
      if reservation
        StockReservation.create!(user_id: reservation.user_id, stock_id: params[:stock_id], invalid_at: DateTime.now + 3.days)
      end
    end
    redirect_to users_book_path(@book.id)
  rescue => e
    p e
    redirect_to :back
  end


  private

  def stock_reservation_params
    params.permit(:stock_id).merge(user_id: current_user.id, invalid_at: DateTime.now + 3.days)
  end

end

app/controllers/users/top_controller.rb
class Users::TopController < UsersController
  def index
    @user = current_user
    @book_search = Book.search(params[:q])
    @books = @book_search.result.includes(:author, :publisher, :genre)
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_filter :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :name) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end

  def after_sign_in_path_for(resource)
    users_top_index_path(resource)
  end

end

app/views/users/books/show.html.erb
<h1> FiNC図書館へようこそ </h1><br>

<div class="navbar navbar-default">
  <div class="navbar-inner">
    <ul class="nav">
      <li><%= link_to "図書検索画面", users_top_index_path %></li>
      <li><%= link_to "図書リクエスト", users_new_books_path %></li>
      <li><%= link_to "ブックマーク", users_bookmarks_path %></li>
      <li><%= link_to "貸出履歴", users_borrowing_histories_path %></li>
      <li><%= link_to "貸出/予約状況", users_borrowings_path %></li>
    </ul>
  </div>
</div>

<div class="book_details_container">
  <p class="rule">
  お客様お一人様あたり、貸出・予約・取り置きまとめて5冊までとさせていただきます。<br>
  5冊超えますと次の予約ができなくなるのでご了承ください。<br>
  また、返却期限を過ぎてしまっている場合も同様です。</p><br>
  <h2>詳細情報</h2><br>
  <div class="books_container">
    <table class="table table-striped" border="3">
      <tr>
        <td>タイトル</td>
        <td>
          <strong><%= @book.title %></strong>
          <% if @user_bookmark %>
            <span class="label label-warning">bookmark</span>
            <%= button_to "ブックマークの取り消し", users_book_bookmark_path(@user_bookmark.book_id, @user_bookmark.id), method: :delete, data: {confirm: "ブックマークを取り消しますか?"}, :method => :delete %>
          <% else %>
            <%= form_for @bookmark, url: users_book_bookmarks_path(@book.id) do |f| %>
              <%= f.submit :ブックマークに入れる %>
            <% end %>
          <% end %>
        </td>
      </tr>

      <tr>
        <td>著者</td>
        <td><%= @book.author.author_name %></td>
      </tr>

      <tr>
        <td>出版社</td>
        <td><%= @book.publisher.publisher_name %></td>
      </tr>

      <tr>
        <td>分野</td>
        <td><%= @book.genre.genre_name %></td>
      </tr>

      <tr>
        <td>図書館保有状況</td>
        <td>合計保有数: <%= @stocks.count %><br>
          <ul>
            <% @stocks.each do |stock| %>
              <li>
                <%= sprintf("%08d", stock.id) %>
                <%= status(stock) %>
              </li>
            <% end %>
          </ul>
        </td>
      </tr>

      <tr>
        <td>あなたの予約状態</td>
        <td>
          <% if @user.stock_borrow(@stocks) %>
            現在<%= sprintf("%08d", @user.stock_borrow(@stocks).stock_id) %>を貸出中<br>
            　返却期限:<%= @user.stock_borrow(@stocks).return_at.to_date %>
        <% else %>
          <% if @user.stock_reserv(@stocks) %>
            現在<%= sprintf("%08d", @user.stock_reserv(@stocks).stock_id) %>を取り置き中<br>
            取り置き有効期限:<%= @user.stock_reserv(@stocks).invalid_at.to_date%><br>
            <%= button_to "予約取り消し", users_book_stock_stock_reservation_path(@book.id, @user.stock_reserv(@stocks).stock_id, @user.stock_reserv(@stocks).id), method: :delete, data: {confirm: "Are you sure??"}, :method => :delete %>
          <% else %>
            <% if @user.book_reserv(@book) %>
              現在予約中。取り置き開始については後日連絡いたします。<br>
              <%= button_to "予約取り消し", users_book_book_reservation_path(@book.id, @user.book_reserv(@book).id), method: :delete, data: {confirm: "Are you sure??"}, :method => :delete %>
            <% else %>
              <% if @user.expired_borrowings %>
                返却期限切れの図書がございます。<br>
                返却できない場合、次の図書の貸出、予約がともにできなくなってしまうので、ご了承ください。
              <% else %>
                <% if  @user.stocks_in_use >= 5 %>
                  現在貸出・予約・取り置き合わせて5冊となっております。<br>
                  予約・取り置きを取り消すか、図書を返却すれば新たな予約が可能になります。
                <% else %>
                  <% unless @book.remaining_stocks.first %>
                    <%= form_for @book_reservation, url: users_book_book_reservations_path(@book.id) do |f| %>
                      <%= f.submit :この本を予約する %>
                    <% end %>
                  <% else %>
                    <%= form_for @stock_reservation, url: users_book_stock_stock_reservations_path(@book.id, @book.remaining_stocks.first.id) do |f| %>
                      <%= f.submit :この本を予約する %>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
        </td>
      </tr>
    </table>
  </div>
</div><br>

<div class="reviews">
  <h2>この本へのレビュー</h2><br>
  <ul>
    <% @book.reviews.each do |review| %>
      <li>
        <%= review.user.name %> |
        <%= review.updated_at %> 
        <% if review.user_id == @user.id %> | 
          <%= link_to "編集", edit_users_book_review_path(review.book_id, review.id) %>
          <%= link_to "削除", users_book_review_path(review.book_id, review.id), method: :delete, data: {confirm: "レビューを本当に削除しますか?"} %>
        <% end %><br>
        <%= review.content %>
      </li>
    <% end %>

    <li>
      <%= form_for @review, url: users_book_reviews_path(@book.id) do |f| %>
        <p>
        <%= f.text_area :content, :size=>"30*20" %><br>
        <%= f.submit :レビューの投稿 %>
        </p>
      <% end %>
  </ul>
  <br><br>

  <h2>この本を借りた人</h2><br>
  <ul>
    <% @book.borrowing_records.each do |borrowing_record| %>
      <li><%= borrowing_record.user.name %> | <%= borrowing_record.borrowed_at.to_date %></li>
    <% end %>
  </ul>
</div>